version: "3.9"
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
     volumes:
       - data:/var/jenkins_home
    env_file:
      - config/.envFile

volumes:
   data:
