apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  containers:
  - name: nodejs
    image: nodejs
    command:
    - cat
    tty: true
  - name: maven
    image: maven
    command:
    - cat
    tty: true
  - name: shell
    image: busybox
    command:
    - cat
    tty: true