# Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: user-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-2
---
# Service accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: administrator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-1
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-2
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-3
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-5
  namespace: kube-system
---
# admin clusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: administrator
  namespace: kube-system
---
# user-1 read cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: user-1
  namespace: kube-system
---
# user-2 read cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: user-2
  namespace: kube-system
---
# roles
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: write-user-1
  namespace: user-1
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-user-2
  namespace: user-2
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-user-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: write-user-1
subjects:
- kind: ServiceAccount
  name: user-1
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-user-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-user-2
subjects:
- kind: ServiceAccount
  name: user-1
  namespace: kube-system