credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          id: "k8s"
          scope: GLOBAL
          secret: "${TOKEN}"
 
jenkins:
  systemMessage: "Jenkins Aitor's Orange Challenge\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Overall/Administer:admin"
      - "Overall/Read:authenticated"
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      credentialsId: "k8s"
      jenkinsUrl: "http://host.docker.internal:8080"
      name: "kubernetes"
      namespace: "default"
      serverCertificate: |
        ${CA}
      serverUrl: "${K8S_HOST}"
      skipTlsVerify: true
      templates:
      - containers:
        - args: "9999999"
          command: "sleep"
          image: "busybox"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "shell"
          workingDir: "/home/jenkins/agent"
        id: "6897dd75-d86e-4c19-a91e-c1a616944e3b"
        label: "default"
        name: "default"
        namespace: "default"
        yamlMergeStrategy: "override"
  # security:
  #   queueItemAuthenticator:
  #     authenticators:
  #       - global:
  #         strategy: triggeringUsersAuthorizationStrategy
  # clouds:
  #   - kubernetes:
  #       connectTimeout: 5
  #       containerCapStr: "10"
  #       credentialsId: "my-k8s-token"
  #       serverUrl: "https://k8s.api.example.com"
  #       skipTlsVerify: true
  #       jenkinsUrl: "https://jenkins.example.com/jenkins"
  #       maxRequestsPerHostStr: "32"
  #       name: "kubernetes"
  #       readTimeout: 15
  #       templates:
  #       - containers:
  #         - args: "^${computer.jnlpmac} ^${computer.name}"
  #           image: "registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7"
  #           livenessProbe:
  #             failureThreshold: 0
  #             initialDelaySeconds: 0
  #             periodSeconds: 0
  #             successThreshold: 0
  #             timeoutSeconds: 0
  #           name: "jnlp"
  #           workingDir: "/tmp"
  #         hostNetwork: false
  #         label: "maven"
  #         name: "maven"
  #         workspaceVolume:
  #           emptyDirWorkspaceVolume:
  #             memory: false
  #         yamlMergeStrategy: "override"
  #       - containers:
  #         - args: "^${computer.jnlpmac} ^${computer.name}"
  #           image: "registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7"
  #           livenessProbe:
  #             failureThreshold: 0
  #             initialDelaySeconds: 0
  #             periodSeconds: 0
  #             successThreshold: 0
  #             timeoutSeconds: 0
  #           name: "jnlp"
  #           workingDir: "/tmp"
  #         hostNetwork: false
  #         label: "nodejs"
  #         name: "nodejs"
  #         workspaceVolume:
  #           emptyDirWorkspaceVolume:
  #             memory: false
  #         yamlMergeStrategy: "override"



unclassified:
  location:
    url: http://localhost:8080/